### PR TITLE
fix(combine): halt middleware evaluation if error in `next()`

### LINKED ISSUE #3898: [hono/combine] Function skipped in some() inside every() is still called
### What version of Hono are you using?

4.7.0

### What runtime/platform is your app running on? (with version if possible)

Node.js

### What steps can reproduce the bug?

Here is a reproducible example:
https://stackblitz.com/edit/node-dtmqxwzv?file=index.ts

```ts
import { serve } from '@hono/node-server';
import { Hono } from 'hono';
import { every, some } from 'hono/combine';

const middleware = every(
  some(
    async (_, next) => {
      console.log('middleware 1');
      await next();
    },
    async (_, next) => {
      console.log('middleware 2', 'should not be called'); // 👈️ Called after "error thrown"
      await next();
    }
  ),
  () => {
    console.log('error thrown');
    throw new Error('some error');
  }
);

const app = new Hono();
app.use(middleware);
app.get('/', (c) => {
  return c.text('ok');
});

serve(app);
```

### What is the expected behavior?

`middleware 2` should be skipped.

### What do you see instead?

`middleware 2`  called after "error thrown".

### Additional information

This issue is also reproducible with the following code. It seems that middleware skipped by some() is called later, regardless of whether every() is used.

```ts
const middleware: MiddlewareHandler = async (c, _next) => {
  await some(
    async (_, next) => {
      console.log('middleware 1');
      await next();
    },
    async (_, next) => {
      console.log('middleware 2', 'should not be called');
      await next();
    }
  )(c, async () => {
    console.log('error thrown');
    throw new Error('some error');
  });
};
```

### PR DESCRIPTION
**Pull request by usualoma**
fixes #3898 

### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code

### CODE REVIEW

**Comment by satoshun00** [comment]
@usualoma 
Thank you for the quick response! I was also looking at this part of the code, and I think this approach makes sense.  

One small point—since `some()` processes multiple middleware using a for-loop, it might be worth verifying in the test code that the call count for the next function is 1.

**Comment by usualoma** [comment]
Hi @satoshun00 
Thank you for your comment!
For the following reasons, I don't think it's necessary to add a test.

* If `next` is called multiple times, the following code will cause an error
    * https://github.com/usualoma/hono/blob/e0cf1566bb7727116683a1641a2cf914c8ef90de/src/compose.ts#L51-L53
* How `next` is handled depends on the internal implementation.

**Comment by usualoma** [comment]
@yusukebe
Would you please review this?

File: src/middleware/combine/index.ts [hunk 1]
```diff
@@ -51,7 +57,9 @@ export const some = (...middleware: (MiddlewareHandler | Condition)[]): Middlewa
         break
       } catch (error) {
         lastError = error
-        continue
+        if (isNextCalled) {
+          break
+        }
```
Comment (yusukebe) [inline src/middleware/combine/index.ts:62]: I think these lines `#L61 - L62` are covered, though Codecov says they are not covered. Should you add more tests?

Comment (usualoma) [reply src/middleware/combine/index.ts:62]: Thanks for your comment.

The refactoring of the e0cf156 test had failed 😢  Fixed in 033d48b.

Comment (yusukebe) [reply src/middleware/combine/index.ts:62]: I see!

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@usualoma Thank you for the quick fix!

@satoshun00 Thank you for raising the issue!
