### PR TITLE
fix(type): degradation of generic type handling

### LINKED ISSUE #3135: bug: JSONParsed type not correctly working for generic type
### What version of Hono are you using?

4.4.13

### What runtime/platform is your app running on?

Nodejs

### What steps can reproduce the bug?

This is happening in the last 2 releases, `v4.4.12` and `v4.4.13`. It seems like the issue is occurring because of this #3074 PR. A community member has created a sample repo - https://github.com/avetisk/dummy-hono-context-helper-type/blob/main/serve.ts

image

The issue is with the generic type (`TData` in this case), if we remove the generic type everything works like normal.

```ts
ok: <TData>(
  data: TData,
  meta?: {
    count?: number;
  }
) => Response &
  TypedResponse<
    { data: TData; meta?: { count?: number } },
    StatusCode,
    "json"
  >;
```

I believe it is occurring because of this new addition in the `JSONParsed` type - 

Screenshot 2024-07-13 at 2 03 02 AM

Even if we `extend` the type, it still gives the error.

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by m-shaka**
### The author should do the following, if applicable
fix #3135 

This works in the use case of the reported issue, I'm not 100% sure why this works though

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

File: src/utils/types.ts [hunk 1]
```diff
@@ -26,7 +26,9 @@ export type IfAnyThenEmptyObject<T> = 0 extends 1 & T ? {} : T
 
 export type JSONPrimitive = string | boolean | number | null
 export type JSONArray = (JSONPrimitive | JSONObject | JSONArray)[]
-export type JSONObject = { [key: string]: JSONPrimitive | JSONArray | JSONObject | object }
+export type JSONObject = {
+  [key: string]: JSONPrimitive | JSONArray | JSONObject | object | InvalidJSONValue
```
Comment (yusukebe) [inline src/utils/types.ts:30]: A quick question. Is adding `InvalidJSONValue` to `JSONObject` our ideal definition? I feel it's weird `JSONObject` has `InvalidJSONValue`.

Comment (m-shaka) [reply src/utils/types.ts:30]: I see. That depends on the meaning of `JSONValue`.

For example, the first parameter of `Context.json` can be an object with a key whose value is `InvalidJSONValue` type.
https://github.com/honojs/hono/blob/bb14b1e5bade8ec4811be9d75d1c1112b7c85d82/src/context.ts#L723-L727

I've just given a quick look but `JSONValue` seems to be used in two ways:
- the type of a candidate value to be converted by `JSON.stringify`
- the type of a **already** converted value by `JSON.stringify`
  - like https://github.com/honojs/hono/blob/4d33e1c0d4fc1efe63e9c2da63d3a4a6b0777fae/src/types.ts#L1902-L1910

I'm not sure but I think it's not so harmful for now. We may need refactoring, though

Comment (yusukebe) [reply src/utils/types.ts:30]: Thank you for the explanation!

How about this? `undefined` is invalid, but having `undefined` as the value of a record is valid:

```diff
diff --git a/src/context.ts b/src/context.ts
index 8d0aa89e..365161fc 100644
--- a/src/context.ts
+++ b/src/context.ts
@@ -180,7 +180,7 @@ type JSONRespondReturn<
       ? JSONValue extends SimplifyDeepArray<T>
         ? never
         : JSONParsed<T>
-      : JSONParsed<T>,
+      : never,
     U,
     'json'
   >
diff --git a/src/utils/types.ts b/src/utils/types.ts
index 3fd17a94..b6cef375 100644
--- a/src/utils/types.ts
+++ b/src/utils/types.ts
@@ -26,7 +26,9 @@ export type IfAnyThenEmptyObject<T> = 0 extends 1 & T ? {} : T

 export type JSONPrimitive = string | boolean | number | null
 export type JSONArray = (JSONPrimitive | JSONObject | JSONArray)[]
-export type JSONObject = { [key: string]: JSONPrimitive | JSONArray | JSONObject | object }
+export type JSONObject = {
+  [key: string]: JSONPrimitive | JSONArray | JSONObject | object | undefined
+}
 export type InvalidJSONValue = undefined | symbol | ((...args: unknown[]) => unknown)

 type InvalidToNull<T> = T extends InvalidJSONValue ? null : T
```

Comment (m-shaka) [reply src/utils/types.ts:30]: In the meaning of the type of a candidate value, it's ok.
You can call `ctx.json({ a: undefined })` and the type of output is `{}`, which is completely correct because the fact that `JSON.stringify` drops keys with `undefined` is the specification.
Same as `ctx.json({ a: Symbol.for("") })` or `ctx.json({ a: () => {} })`.

However, in the meaning of the latter case (used as a type constraint of `TypedResponse`), it's not correct. It expects types being proceeded by `JSONParsed`, that never have keys with `undefined`, `symbol`, or `function` type.
But, my guess is that in most cases `TypedResponse` is used through `JSONRespondReturn` or like that, and `JSONValue` is used here only for deciding the response format, and types like `{ a: undefined }` should be treated as `'json'` format.
That's why I said it's not so harmful is that 

(I'm not confident if I understand what you mean. Sorry if not.)

Comment (yusukebe) [reply src/utils/types.ts:30]: @m-shaka

Understood well. You are right that the definition of `JSONObject` is good for now. Sorry for wasting your time. Thanks!

**Review by yusukebe — APPROVED** [review]
LGTM!

File: src/utils/types.ts (hunk 1 above)
Comment (m-shaka) [reply src/utils/types.ts:30]: No way! Thank you for your patience!
