### PR TITLE
fix(dev): preserve original handler in [composedHandler].

### LINKED ISSUE #1868: `showRoutes` shows handler as `[middleware]` if subApp has a custom error handler
### What version of Hono are you using?

3.11.11

### What runtime/platform is your app running on?

any

### What steps can reproduce the bug?

```ts
// src/dev-subapp.ts
import { Hono } from 'hono'
import { showRoutes } from 'hono/dev'

const subApp = new Hono()

subApp.get('/', (c) => c.json(0))
subApp.onError((_, c) => c.json(0))

const app = new Hono()
app.route('/', subApp)

showRoutes(app, {
  verbose: true
})
```

```txt
tsx src/dev-subapp.ts
```

### What is the expected behavior?

It prints as below:

```txt
GET  /
       [handler]
```

### What do you see instead?

```txt
GET  /
       [middleware]
```

### Additional information

If comment out the following line, it works correctly.

```ts
const subApp = new Hono()

subApp.get('/', (c) => c.json(0))
// subApp.onError((_, c) => c.json(0)) // comment out

const app = new Hono()
app.route('/', subApp)
```

### PR DESCRIPTION
**Pull request by usualoma**
Fixes #1868

How about this solution?

### If we do more

I suppose we could add the information "added from sub pp" in inspectRoutes. But I didn't go that far at this point, because I think it's enough to fix the problem in #1868.

### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

File: src/hono-base.ts [hunk 1]
```diff
@@ -23,6 +23,8 @@ import type {
 } from './types'
 import { getPath, getPathNoStrict, getQueryStrings, mergePath } from './utils/url'
 
+export const composedHandler = Symbol('composedHandler')
```
Comment (yusukebe) [inline src/hono-base.ts:26]: Since `composedHandler` is a constant like `METHODS`, maybe `COMPOSED_HANDLER` would be better. What do you think?

```ts
export const COMPOSED_HANDLER = Symbol('composedHandler')
```

**Comment by yusukebe** [comment]
@usualoma Happy New Year!

I think this way is good. And I also think we don't need `added from sub app` now. I'v left one comment, please check it.

**Comment by usualoma** [comment]
@yusukebe Happy New Year 🎍 
You're right, I did change it! 
239db3d

**Comment by yusukebe** [comment]
@usualoma 

Thanks! I'll merge this now.
