### PR TITLE
fix(types): JSONParsed infer unknown values

### LINKED ISSUE #4368: RPC client infers object with an `unknown` property as `never`
### What version of Hono are you using?

4.9.4

### What runtime/platform is your app running on? (with version if possible)

Node

### What steps can reproduce the bug?

Hi! Great library. Thanks for all your work. I've run into the following behavior that's tripped me up a couple of times. 

When a route returns an object with a property of type `unknown`, hono client infers that return type as `never`.

While I usually don't _mean_ to return an `unknown` property, this particular behavior was unexpected to me and pretty hard to debug. I started gradually removing parts of my application until I found the problem property. 

Is this a bug or maybe something to document?

Reproduction:

```typescript
import { Hono } from "hono";
import { hc } from "hono/client";

const app = new Hono()
  .get("/expected", (c) => {
    const data: { foo: string; bar: string } = { foo: "hello", bar: "world" };
    return c.json(data);
  })
  .get("/unexpected", (c) => {
    // Return an object with a property of type unknown
    const data: { foo: string; bar: unknown } = { foo: "hello", bar: 123 };
    return c.json(data);
  });

type AppType = typeof app;

const client = hc<AppType>("/");

async function testClient() {
  const expectedRes = await client.expected.$get();
  if (expectedRes.ok) {
    const data = await expectedRes.json(); // Type: { foo: string; bar: string }
    console.log(data.foo); // ✅ Works fine
  }

  const unexpectedRes = await client.unexpected.$get();
  if (unexpectedRes.ok) {
    const data = await unexpectedRes.json(); // Type: never ❌
    console.log(data.foo); // TypeScript error: Property 'foo' does not exist on type 'never'
  }
}
```

https://www.typescriptlang.org/play/?#code/PTAEFkEsDtIWwIYBtQCcCmAHVB7AJgK4DGALpDtKDgGagASFOoASgAoDCoB06AHpulLo8oEgE8BoGNXQZoRdACgQoAOoALdJQRocBEulDqE0PEllp0JAqmgBnUCaoAjAFaCSoAO6QS6x6DYOAKo4qISwo4OAOTcANbQOF7Q0QA0ymB+hmycREiQWp7Ssg5ZlnaYFHaG4pIIMTwAbrLRUvYGCCI0opqOpATI4QIAdIqK8JWhoADe9IygAL6g1LhwoABE6ozrANzjcJOes+pEi8urG1uJwHkF0CS7YyrsGAgGAXYT5o6YmN6+-h0uH0NWMngw1lsDicODcHlARAoJAQMBgAHNQLFoAkkilFIj2j8-gBeUA8LxzRIACgAlIpQKBhmirFT1sA+AIhHh1qlQFSiDTQMSAHwzekMhFVTx4N4IABcM2WOBwCrsJFQ6J2oGcCFQqvV6LOpNm1GVCs26CQSBwPO1uvNXhwqCQ3MWewllkhlCIw1cdgoVJlyJp7sWdIZTJZbO4HI8wlt-MFIrFHpUzCsNm0lFh7lI-z8ASCITC3VqhniiWS4oZBLVoCD8sVppVoDVGugaK1Or1XGxlcoS2NSpbFqtNt53YVAEYAEwAZjd1c9mYRvv90EDspD4oW28UZdAAEFfgAVCJCoboboIX57fFShH5QoXk4AHmPmDPAmFrOA6z39RiPIyzcKQ5CUAYarsE+9y0imkqErGXLpg4pIIF4KKeLchTDEhBh4MMAAkzIkLSoaQLQVJ4cIKHDDgcSCtMS61tKsoXuhmGgNReC0X6AYhqAKhfugCommarYGh2Xb2hJ7YYgszFVDg5jDNaaKbsiwzNgJKiAKDkahOnEDjUDASgMgp4osb23EoexGG+I+dwkMMMb8HGBHESy24MhRfKuZy+G0fRjGKYSDZ2Zx-nubx65kYJYDCQqTQWIAMuShf6KlqRpCBacqOkJREADKRAapgniyLgPasLgxZiJizatHgODoA4iTlbwkB1hQl6YslqDRDuigKUAA

### What is the expected behavior?

For the route that returns `{ foo: string; bar: unknown }`, I'd expect the inferred client type to be `{ foo: string; bar: unknown }`

### What do you see instead?

Instead, the client inferred type is `never`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by BarryThePenguin**
Changes `JSONParsed` so it will infer `unknown` values as `JSONValue`.

I also included handling for `bigint` so `JSONParsed` will be `never`, indicating that an error will be thrown.

fixes #4368

### CODE REVIEW

File: src/context.ts [hunk 1]
```diff
@@ -194,21 +194,12 @@ interface JSONRespond {
...
-  TypedResponse<
-    SimplifyDeepArray<T> extends JSONValue
-      ? JSONValue extends SimplifyDeepArray<T>
-        ? never
-        : JSONParsed<T>
-      : never,
-    U,
-    'json'
-  >
+> = Response & TypedResponse<JSONParsed<T>, U, 'json'>
```
Comment (BarryThePenguin) [inline src/context.ts:202]: I think this change could be a seperate PR.

From what I understand `JSONParsed` already contains types that do the same thing as `SimplifyDeepArray`, specifically

```ts
...
  : T extends ReadonlyArray<unknown>
  ? { [K in keyof T]: JSONParsed<InvalidToNull<T[K]>> }
  : ...
```

compared with `SimplifyDeepArray`

```ts
type SimplifyDeepArray<T> = T extends any[]
  ? { [E in keyof T]: SimplifyDeepArray<T[E]> }
  : Simplify<T>
```

Comment (yusukebe) [reply src/context.ts:202]: Indeed. We can remove `SimplifyDeepArray`. For now, I'll merge this PR.

**Comment by yusukebe** [comment]
@BarryThePenguin 

Thank you! Looks good.
