### PR TITLE
fix(context): encode the redirect location

### LINKED ISSUE #4295: Context.redirect doesn't accept a URL which contains multibyte characters
### What version of Hono are you using?

4.8.5

### What runtime/platform is your app running on? (with version if possible)

Node v20.19.2

### What steps can reproduce the bug?

```
app.get("/", (c) => {
  return c.redirect("https://ja.wikipedia.org/wiki/小麦粉");
});
```

Here is the reproduction repo: https://github.com/yayugu/hono-bug-report/tree/2025-07-22-redirect

```bash
$ pnpm i
$ pnpm dev
# Then access to http://localhost:3000
```

### What is the expected behavior?

Just redirect to the page.

### What do you see instead?

The error output:
```
TypeError: Cannot convert argument to a ByteString because the character at index 30 has a value of 23567 which is greater than 255.
    at webidl.converters.ByteString (node:internal/deps/undici/undici:3889:17)
    at _Headers.set (node:internal/deps/undici/undici:8921:35)
    at Context.header (file:///home/yayugu/hono-bug-report/node_modules/.pnpm/hono@4.8.5/node_modules/hono/dist/context.js:100:15)
    at Context.redirect (file:///home/yayugu/hono-bug-report/node_modules/.pnpm/hono@4.8.5/node_modules/hono/dist/context.js:167:10)
    at Array.<anonymous> (/home/yayugu/hono-bug-report/src/index.tsx:7:12)
    at #dispatch (file:///home/yayugu/hono-bug-report/node_modules/.pnpm/hono@4.8.5/node_modules/hono/dist/hono-base.js:188:38)
    at fetch (file:///home/yayugu/hono-bug-report/node_modules/.pnpm/hono@4.8.5/node_modules/hono/dist/hono-base.js:214:26)
    at Server.<anonymous> (file:///home/yayugu/hono-bug-report/node_modules/.pnpm/@hono+node-server@1.17.1_hono@4.8.5/node_modules/@hono/node-server/dist/index.mjs:487:13)
    at Server.emit (node:events:524:28)
    at parserOnIncoming (node:_http_server:1141:12)
```

#### Necessity
I found this during implementing the dynamic redirect, for example:

```javascript
const paramA = c.req.param("paramA");
c.redirect(`/new-url/${paramA}`);
```

Type check didn't help and found the bug after released the code. It's easy to wrap with encodeURI(), by it would super nice if redirect() function cares the encoding.

#### Cause and Design of the Fix
Node's Header object doesn't accept multibyte characters https://github.com/nodejs/node/issues/42579.

Context.redirect() is currently just by pass the value. It should accept any valid URL and encode that if necessary.
The complicated thing is if the path / URI is already encoded, it must not re-encode that. The pseudo code would be

```javascript
if (path.hasNonASCII() {
  path = encodeURI(path);
}
header.set(path);
```

### PR DESCRIPTION
**Pull request by yayugu**
Fixes #4295

### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [x] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

File: src/context.ts [hunk 1]
```diff
@@ -285,6 +285,24 @@ const setDefaultContentType = (contentType: string, headers?: HeaderRecord): Hea
   }
 }
 
+/**
+ * This function ensures that the string is safely encoded,
+ * and not double-encoded.
+ * The input string may or may not escaped by encodeURI.
+ */
+const safeEncodeURI = (str: string) => {
```
Comment (yusukebe) [inline src/context.ts]: I was a little unsure about this, but I think it would be better to move `safeEncodeURI` to `src/utils/url.ts`. It is only used in `src/contex.ts`, so it is not necessary, but since all other functions related to URL/URI are in that file, it would be better.

In that case, writing unit tests for `safeEncodeURI` in `src/utils/url.test.ts` will be good.

File: src/context.ts [hunk 2]
```diff
@@ -285,6 +285,24 @@ const setDefaultContentType = (contentType: string, headers?: HeaderRecord): Hea
...
+  try {
+    // decodeURI will throw if str contains %
+    // In that case, we can assume that str is not encoded
+    return encodeURI(decodeURI(str))
```
Comment (yusukebe) [inline src/context.ts]: I think this implementation is good. Using the exception makes the code shorter.

File: src/context.ts (hunk 1 above)
Comment (yayugu) [reply src/context.ts]: Cool, I don't have any preference of that, moved

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@yayugu 

Looks good to me! I'll merge this and release a new version. Thank you!

**Comment by NamesMT** [comment]
Hi @yusukebe , @yayugu 

The `safeEncodeURI` does not seems to be working perfectly.
I'm experiencing double encoding with the redirectUrl returned by [`msal-node`](https://github.com/AzureAD/microsoft-authentication-library-for-js) (Microsoft EntraID auth)

Raw url: `https://login.microsoftonline.com/redacted-id&scope=email%20openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Fredacted-domain.org%2Fapi%2Fauth%2Fcallback&client-request-id=redacted-id&response_mode=query&client_info=1&x-client-SKU=msal.js.node&x-client-VER=3.6.4&x-client-OS=linux&x-client-CPU=x64&response_type=code&code_challenge=7C75MO8zdoJZn7_sIpxcFEQzPvzWIMzD2tUf-lqevR0&code_challenge_method=S256`

After `safeEncodeURI`: `https://login.microsoftonline.com/redacted-id&scope=email%20openid%20profile%20offline_access&redirect_uri=https%253A%252F%252Fredacted-domain.org%252Fapi%252Fauth%252Fcallback&client-request-id=redacted-id&response_mode=query&client_info=1&x-client-SKU=msal.js.node&x-client-VER=3.6.4&x-client-OS=linux&x-client-CPU=x64&response_type=code&code_challenge=7C75MO8zdoJZn7_sIpxcFEQzPvzWIMzD2tUf-lqevR0&code_challenge_method=S256`

The `redirect_uri` is double encoded and breaks the site's login.

**Comment by yusukebe** [comment]
@NamesMT  thank you for the report. Exactly, it does not work correctly.

**Comment by yusukebe** [comment]
@yayugu @NamesMT I'm working on it.

**Comment by anthonymclaughlin** [comment]
I'm still getting double encoding after updating to v4.8.8.

Calling this redirect URL:

`return c.redirect('https://api.workos.com/user_management/authorize?client_id=1234&provider=authkit&redirect_uri=https%3A%2F%2Faccount.localhost.direct%3A8081%2Fapi%2Fauth%2Fcallback&response_type=code', 302);`

results in `redirect_url` being double encoded.

This code worked in v4.8.5.

**Comment by yusukebe** [comment]
@anthonymclaughlin Thank you for the report. I'll work on fixing it.

**Comment by yusukebe** [comment]
Hey @anthonymclaughlin 

It's fixed with the latest `4.8.9`.
