### PR TITLE
fix(service-worker): make `fire()` fallback behavior consistent with `handle()`

### LINKED ISSUE #4632: The default behavior on 404 in handle() and fire() seems inconsistent and not documented
### What version of Hono are you using?

4.11.3

### What runtime/platform is your app running on? (with version if possible)

Service Worker

### What steps can reproduce the bug?

1. If I use `handle(app)` in fetch event handler in service worker and when my app returns 404, it seems `handle(app)` automatically fetches original request again. This is the default behavior because `opts.fetch` is defined by default. I couldn't find about this behavior (and how to disable this) in the documentation. (sorry if I was overlooking)
https://github.com/honojs/hono/blob/28452f06319ef12df94b826450f36486e286565d/src/adapter/service-worker/handler.ts#L18-L23
https://github.com/honojs/hono/blob/28452f06319ef12df94b826450f36486e286565d/src/adapter/service-worker/handler.ts#L30-L32

2. If I use `fire(app)` instead, it won't do that by default, because default value of options.fetch is `undefined` unlike `handle(app)`. The documentation says "The `fire()` function automatically calls `addEventListener('fetch', handle(app))` for you," but that's not entirely correct.
https://github.com/honojs/hono/blob/28452f06319ef12df94b826450f36486e286565d/src/adapter/service-worker/index.ts#L28-L36

### What is the expected behavior?

I don't know which behavior is better, but I think it would be better to have one consistent (though it might be a breaking change...) and it should be documented.

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yusukebe**
Fixes #4632

### The author should do the following, if applicable

- [ ] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

File: src/adapter/service-worker/index.ts [hunk 1]
```diff
@@ -27,9 +27,7 @@ import type { HandleOptions } from './handler'
  */
 const fire = <E extends Env, S extends Schema, BasePath extends string>(
   app: Hono<E, S, BasePath>,
-  options: HandleOptions = {
-    fetch: undefined,
```
Comment (yusukebe) [inline src/adapter/service-worker/index.ts:31]: I can't remember why I made the default value of `fetch` `undefined`, or whether it was intended. But the JSDoc said `fire` means `addEventListener('fetch', handle(app, options))`. So to make it consistent, this PR's change is meaningful.
