### PR TITLE
fix(types): allow not to set `skipLibCheck`

### LINKED ISSUE #1200: using hono requires skipLibCheck
Hi,

I've just tried adding your library to my project. However, simply running `new Hono();` breaks my typescript project due to numerous type issues with your bundled types; some of your types expect the global `Request` to be a DOM request object, but this is not true in the workers environment.

Passing `skipLibCheck: true` to my tsconfig suppresses the errors, which I notice is what the [hono repo itself does in its own tsconfig](https://github.com/honojs/hono/blob/4b2dfb824ba68c6dd03ea93ba60649a95d370e80/tsconfig.json#L10).

However, this is definitely not a good thing to do, as it disables ALL type checking for all dependencies.

Here is a demonstration. Any ideas? I've also included my tsconfig below. 

```
~/P/server main• 1s ❱ tsc --noEmit --project .
~/P/server main• ❱ echo "Note: no type errors in my project prior to adding hono"
Note: no type errors in my project prior to adding hono
~/P/server main• ❱ npm install hono

added 1 package, and audited 915 packages in 883ms

152 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
~/P/server main• 1s ❱ echo -e "import { Hono } from 'hono';\n const app = new Hono();" >> src/worker.ts
~/P/server main• ❱ tsc --noEmit --project .
../node_modules/hono/dist/types/client/types.d.ts:22:18 - error TS2430: Interface 'ClientResponse<T>' incorrectly extends interface 'Response'.
  The types returned by 'json()' are incompatible between these types.
    Type 'Promise<T>' is not assignable to type 'Promise<T>'. Two different types with this name exist, but they are unrelated.
      Type 'T' is not assignable to type 'T'. Two different types with this name exist, but they are unrelated.
        'T' could be instantiated with an arbitrary type which could be unrelated to 'T'.

22 export interface ClientResponse<T> extends Response {
                    ~~~~~~~~~~~~~~

  ../node_modules/hono/dist/types/client/types.d.ts:22:33
    22 export interface ClientResponse<T> extends Response {
                                       ~
    This type parameter might need an `extends T` constraint.

../node_modules/hono/dist/types/request.d.ts:51:21 - error TS2304: Cannot find name 'RequestRedirect'.

51     get redirect(): RequestRedirect;
                       ~~~~~~~~~~~~~~~

../node_modules/hono/dist/types/request.d.ts:54:18 - error TS2304: Cannot find name 'RequestCache'.

54     get cache(): RequestCache;
                    ~~~~~~~~~~~~

../node_modules/hono/dist/types/request.d.ts:55:24 - error TS2304: Cannot find name 'RequestCredentials'.

55     get credentials(): RequestCredentials;
                          ~~~~~~~~~~~~~~~~~~

../node_modules/hono/dist/types/request.d.ts:58:17 - error TS2304: Cannot find name 'RequestMode'.

58     get mode(): RequestMode;
                   ~~~~~~~~~~~

../node_modules/hono/dist/types/request.d.ts:60:26 - error TS2304: Cannot find name 'ReferrerPolicy'.

60     get refererPolicy(): ReferrerPolicy;
                            ~~~~~~~~~~~~~~


Found 6 errors in 2 files.

Errors  Files
     1  ../node_modules/hono/dist/types/client/types.d.ts:22
     5  ../node_modules/hono/dist/types/request.d.ts:51
~/P/server main• | 2 ❱
```

```tsconfig
...
  "compilerOptions": {
    "lib": ["es2022"],
    "types": ["@cloudflare/workers-types"]
  },
...
  ```

### PR DESCRIPTION
**Pull request by yusukebe**
Currently, if a user doesn't set `skipLibCheck` to `true` in `tsconfig.json`, it throws the error as shown below:

SS

To fix it, in this PR, I've done the following:

1. Removed unnecessary properties that are not in `@cloudflare/workers-types` and `DOM` from `Request`.
2. Created `FetchEventLike` to ensure compatibility between environments where there is `FetchEvent` and where there isn't.
3. Added the properties in `Response` to `ClientResponse`.

This change allows it to pass `tsc` and simplifies `tsconfig.json`:

SS

```ts
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "node",
    "strict": true,
    "lib": [
      "esnext"
    ],
    "types": [
      "@cloudflare/workers-types",
    ],
  },
}
```

And if you don't want to use `@cloudflare/workers-types`:

```ts
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "node",
    "strict": true,
    "lib": [
      "esnext",
      "DOM"
    ],
    "types": [
      "node"
    ],
  },
}
```

Fixes #1200

### CODE REVIEW

File: src/client/types.ts [hunk 1]
```diff
@@ -26,10 +26,24 @@ type ClientRequest<S extends Data> = {
...
+  clone(): Response
   json(): Promise<T>
+  text(): Promise<string>
+  blob(): Promise<Blob>
+  formData(): Promise<FormData>
+  arrayBuffer(): Promise<ArrayBuffer>
 }
 
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
+export interface Response extends ClientResponse<any> {}
```
Comment (aroman) [inline src/client/types.ts:45]: same comment as `src/client/deno.ts`

File: deno_dist/client/types.ts [hunk 2]
```diff
@@ -26,10 +26,24 @@ type ClientRequest<S extends Data> = {
...
+  clone(): Response
   json(): Promise<T>
+  text(): Promise<string>
+  blob(): Promise<Blob>
+  formData(): Promise<FormData>
+  arrayBuffer(): Promise<ArrayBuffer>
 }
 
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
+export interface Response extends ClientResponse<any> {}
```
Comment (aroman) [inline deno_dist/client/types.ts:45]: perhaps you could use `unknown` instead of `any` here? like:

`export interface Response extends ClientResponse<unknown> {}`

Comment (yusukebe) [reply deno_dist/client/types.ts:45]: You are right! It should be `unknown`.

**Comment by yusukebe** [comment]
Thanks! Merging!
