### PR TITLE
fix(jsx): align link hoisting and dedupe with React 19

### LINKED ISSUE #4789: link rel=canonical is silently removed when it shares the same href as link rel=alternate hreflang
First of all, thank you for building Hono — it's been a joy to work with, especially the JSX renderer's automatic head hoisting. I ran into a small edge case while implementing hreflang + canonical links, and I'd love to help get it fixed.

### Summary

When using `jsxRenderer`, a `<link rel="canonical">` tag is silently dropped from the rendered HTML if a `<link rel="alternate" hreflang="...">` tag shares the same `href`.

### Reproduction

On a localized EN page (e.g. `/en/about`), the canonical URL and the `hreflang="en"` alternate URL are identical by design. When both are declared in the renderer:

```tsx
<link rel="canonical" href="https://example.com/en/about" />
<link rel="alternate" hreflang="en" href="https://example.com/en/about" />
<link rel="alternate" hreflang="ja" href="https://example.com/ja/about" />
```

The rendered HTML becomes:

```html
<!-- canonical is missing -->
<link rel="alternate" hreflang="en" href="https://example.com/en/about" />
<link rel="alternate" hreflang="ja" href="https://example.com/ja/about" />
```

### Root Cause

In `src/jsx/intrinsic-element/common.ts`, the deduplication key for `link` elements is:

```ts
const deDupeKeyMap = {
  link: ["href"],
}
```

The deduplication logic in `src/jsx/intrinsic-element/components.ts` uses **OR semantics**: if *any* key in `deDupeKeys` matches an existing tag's props, the new tag is considered a duplicate.

Because `rel="canonical"` and `rel="alternate" hreflang="en"` share the same `href`, the canonical tag is treated as a duplicate of the already-registered alternate tag and removed from the buffer.

### Expected Behavior

Two `<link>` elements should only be considered duplicates when **all** identifying attributes match. Specifically, `rel` (and `hreflang` for alternate links) should be part of the deduplication key.

### Proposed Fix

**`src/jsx/intrinsic-element/common.ts`** — add `rel` and `hreflang` to the `link` dedup keys:

```ts
const deDupeKeyMap = {
  link: ["href", "rel", "hreflang"],
}
```

**`src/jsx/intrinsic-element/components.ts`** — change OR semantics to AND semantics for multi-key deduplication:

```ts
// Before (OR: any key match → duplicate)
for (const key of deDupeKeys) {
  if ((tagProps?.[key] ?? null) === props?.[key]) {
    duped = true
    break LOOP
  }
}

// After (AND: all keys must match → duplicate)
const allMatch = deDupeKeys.every(
  (key) => (tagProps?.[key] ?? null) === (props?.[key] ?? null)
)
if (allMatch) {
  duped = true
  break LOOP
}
```

With this fix:

| Scenario | Before | After |
|---|---|---|
| `rel="canonical" href="X"` vs `rel="alternate" href="X"` | ❌ deduped (canonical removed) | ✅ kept (different `rel`) |
| `rel="alternate" hreflang="en" href="X"` vs `rel="alternate" hreflang="ja" href="X"` | ❌ deduped | ✅ kept (different `hreflang`) |
| Two identical `rel="canonical" href="X"` | ✅ deduped | ✅ deduped |

### Workaround

Use `raw()` from `hono/html` to bypass Hono JSX's `<link>` processing:

```tsx
import { raw } from 'hono/html'

// In jsxRenderer:
{raw(`<link rel="canonical" href="${canonicalUrl}">`)}
```

### Environment

- Hono: 4.11.9
- Reproduction: placing `<link rel="canonical">` and `<link rel="alternate" hreflang>` with the same `href` in `jsxRenderer`

I'm happy to send a PR with the fix if this looks reasonable. Thanks again for all your work on Hono!

### PR DESCRIPTION
**Pull request by usualoma**
fixes #4789

### Summary

Because React 19 appears to dedupe only link elements that are stylesheet + precedence, this PR aligns Hono JSX runtime link hoisting/dedupe behavior with that model.

It fixes over-deduplication by href (for canonical / alternate / preload / icon / preconnect, etc.) and narrows dedupe to stylesheet links with precedence only.

As shown below, the list of links with issues reported in the issue will also remain without being deduplicated.

https://github.com/honojs/hono/compare/fix-hoisting-link-element-3?expand=1#diff-7077a729697655835dd10a0638c9e8ffaad5aef95597d9f409cc4e3f3fb9f848R374-R384

### Compatibility

- No public API or type changes.
- Changes are limited to internal JSX runtime `link` hoisting/dedupe behavior and tests.

### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code

### CODE REVIEW

**Comment by usualoma** [comment]
@yusukebe
Would you please review this?

**Comment by usualoma** [comment]
Oops

**Comment by usualoma** [comment]
@yusukebe 
My bad. I've fixed it.

File: src/jsx/intrinsic-element/common.ts [hunk 1]
```diff
@@ -9,3 +11,13 @@ export const deDupeKeyMap: Record<string, string[]> = {
 export const domRenderers: Record<string, Function> = {}
 
 export const dataPrecedenceAttr = 'data-precedence'
+
+export const isStylesheetLinkWithPrecedence = (props: Props): boolean =>
+  props.rel === 'stylesheet' && 'precedence' in props
+
+export const shouldDeDupeByKey = (tagName: string, props: Props, supportSort: boolean): boolean => {
```
Comment (yusukebe) [inline src/jsx/intrinsic-element/common.ts]: Can you apply the flowing patch to remove the lint error though CI does not fail?

```diff
diff --git a/src/jsx/intrinsic-element/common.ts b/src/jsx/intrinsic-element/common.ts
index aaa2ce0c..937c0974 100644
--- a/src/jsx/intrinsic-element/common.ts
+++ b/src/jsx/intrinsic-element/common.ts
@@ -15,7 +15,11 @@ export const dataPrecedenceAttr = 'data-precedence'
 export const isStylesheetLinkWithPrecedence = (props: Props): boolean =>
   props.rel === 'stylesheet' && 'precedence' in props

-export const shouldDeDupeByKey = (tagName: string, props: Props, supportSort: boolean): boolean => {
+export const shouldDeDupeByKey = (
+  tagName: string,
+  _props: Props,
+  supportSort: boolean
+): boolean => {
   if (tagName === 'link') {
     return supportSort
   }
```

**Comment by usualoma** [comment]
@yusukebe 
Fixed in 9d63042 and improved test coverage in 2b0d6d3.

**Comment by yusukebe** [comment]
@usualoma 

Thank you! Looks good.
