### PR TITLE
fix(request): `req.json()` keeps the content as is

### LINKED ISSUE #4259: TypeError: Body is unusable
### What version of Hono are you using?

4.8.3

### What runtime/platform is your app running on? (with version if possible)

Node

### What steps can reproduce the bug?

Add 2x `zValidators` for path/middleware for json, header and try to access raw body text in route handler.

From my investigations, [this](https://github.com/honojs/hono/blob/main/src/validator/validator.ts#L78) is causing the error. If we clone the json using `await c.req.raw.clone().json()`, it works fine.

Example using create hono app:
```
import { serve } from "@hono/node-server";
import { Hono } from "hono";
import { z } from "zod";
import { zValidator } from "@hono/zod-validator";

const schema = z.object({  mock: z.string() });

const app = new Hono();

app
  .get("/", (c) => {
    return c.text("Hello Hono!");
  })
  .post(
    "/",
    zValidator("header", schema),
    zValidator("json", schema),
    async (c) => {
      // causes error
      console.log(await c.req.raw.clone().text());

      return c.text("Hello Hono!");
    }
  );

serve(
  {
    fetch: app.fetch,
    port: 3000,
  },
  (info) => {
    console.log(`Server is running on http://localhost:${info.port}`);
  }
);
```

### What is the expected behavior?

I'm able to use multiple zValidators - especially for json & header - and still access the raw body.

### What do you see instead?

```
TypeError: unusable
    at Request.clone (node:internal/deps/undici/undici:9942:17)
    at Request.value (file:///Users/pete/Development/poc/hono-bug/node_modules/.pnpm/@hono+node-server@1.14.4_hono@4.8.3/node_modules/@hono/node-server/dist/index.mjs:122:40)
    at <anonymous> (/Users/pete/Development/poc/hono-bug/src/index.ts:21:35)
    at dispatch (file:///Users/pete/Development/poc/hono-bug/node_modules/.pnpm/hono@4.8.3/node_modules/hono/dist/compose.js:22:23)
    at file:///Users/pete/Development/poc/hono-bug/node_modules/.pnpm/hono@4.8.3/node_modules/hono/dist/compose.js:22:46
    at file:///Users/pete/Development/poc/hono-bug/node_modules/.pnpm/hono@4.8.3/node_modules/hono/dist/validator/validator.js:81:11
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async dispatch (file:///Users/pete/Development/poc/hono-bug/node_modules/.pnpm/hono@4.8.3/node_modules/hono/dist/compose.js:22:17)
    at async file:///Users/pete/Development/poc/hono-bug/node_modules/.pnpm/hono@4.8.3/node_modules/hono/dist/validator/validator.js:81:5
    at async dispatch (file:///Users/pete/Development/poc/hono-bug/node_modules/.pnpm/hono@4.8.3/node_modules/hono/dist/compose.js:22:17)
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yusukebe**
Fixes #4259

### The author should do the following, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `bun run format:fix && bun run lint:fix` to format the code
- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

File: src/request.ts [hunk 1]
```diff
@@ -243,7 +243,7 @@ export class HonoRequest<P extends string = '/', I extends Input['out'] = {}> {
    * ```
    */
   json<T = any>(): Promise<T> {
-    return this.#cachedBody('json')
+    return this.#cachedBody('text').then((text: string) => JSON.parse(text))
```
Comment (ysm-dev) [inline src/request.ts:246]: @yusukebe 

I think this broken `req.bodyCache.json` ?

I got `undefined` for `req.bodyCache.json` after this commit

Comment (yusukebe) [reply src/request.ts:246]: @ysm-dev 

`req.bodyCache` is not designed for end-users, but can you share the code to reproduce it?

**Comment by nicougou** [comment]
@yusukebe i noticed a regression, but maybe for a use-case that is not supported, but it break the whole concept of my app, so i'd like to share it:

```
// fetch the request body
const initialBody = await c.req.json();

// change the body
initialBody.foo = 'bar';

// get the body again
const body2 = await c.req.json();

// show that both object are equals
console.info('Show body', {
  body1: JSON.stringify(initialBody),
  body2: JSON.stringify(body2),
});
```

Before this PR, my `initialBody` and `body2` were exact matches.
After this PR, a new call to `c.req.json()` is not returning the value i updated before.

While it might not be an expected usage, this conceptually breaks what i was relying on (be able to modify the request body).

Am i on the wrong side of things on this one ? 🤔

**Comment by yusukebe** [comment]
Hi @nicougou 

The behavior has changed, as expected. The return value from `c.req.json()` should not be a reference, but should be an actual object.

**Comment by nicougou** [comment]
> Hi @nicougou
> 
> The behavior has changed, as expected. The return value from `c.req.json()` should not be a reference, but should be an actual object.

@yusukebe i see 🤔 

Then is there a way around my use-case, being able to edit the request body so that it shows in `c.req.json()` down the road ?
Or is that an anti-pattern that will make me rewrite my app ? 😅

**Comment by yusukebe** [comment]
@nicougou 

I don't understand your use case well, but how about using `c.set()`/`c.get()` to keep the value if you want to share it between middleware or handlers? `c.req` is read-only, so you can not replace it.

**Comment by nicougou** [comment]
> @nicougou
> 
> I don't understand your use case well, but how about using `c.set()`/`c.get()` to keep the value if you want to share it between middleware or handlers? `c.req` is read-only, so you can not replace it.

@yusukebe My use case, high level is that i'm working on top of an existing app (some kind of forking of an hono-based app).

- The exiting app already has handlers, that uses `c.req.json()` (as they should).
- I wish not to change the handlers code (easier to get upstream updates)
- I created a global middleware that correct/update/fixes the incoming payload, before the existing handlers are called

To that end, my middleware is currently doing transformations to the request body, which worked perfectly until this PR came along.
I have to admit maybe it worked by pure luck due to an underlaying issue, but i had a lot of my logic running on this:

- body transformations
- headers transformations (by replacing the `c.req.raw`, which still works 🤞)

Having a way to transform the request body in a middleware didn't see like a clear anti-pattern (well, i'm biased on that since i relied on it ^^), and while i could indeed use `c.set()`/`c.get()`, i really liked the idea of having my other handlers to keep using `c.req.json()`, and leave the body transformation complexity to my custom middelware.
